src/Entity/Insta.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use ApiPlatform\Core\Annotation\ApiFilter;
use ApiPlatform\Core\Bridge\Doctrine\Orm\Filter\RangeFilter;
use ApiPlatform\Core\Bridge\Doctrine\Orm\Filter\ExistsFilter;
use ApiPlatform\Core\Bridge\Doctrine\Orm\Filter\SearchFilter;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ApiResource()
 * @ApiFilter(SearchFilter::class, properties={"insta_type": "exact", "id": "exact", "user_username": "exact", "insta_id": "exact", "tags":"partial"})
 * @ApiFilter(RangeFilter::class, properties={"latitude", "longitude"})
 * @ApiFilter(ExistsFilter::class, properties={"insta_id", "responseJson"})
 * @ORM\Entity(repositoryClass="App\Repository\InstaRepository")
 */
class Insta
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $caption;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $link;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $user_username;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $insta_type;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $insta_id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $low_resolution;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $standard_resolution;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $thumbnail;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $tags;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $location;

    /**
     * @ORM\Column(type="integer", length=255, nullable=true)
     */
    private $created_time;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=6, nullable=true)
     */
    private $latitude;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=6, nullable=true)
     */
    private $longitude;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $responseJson;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $likes;


    public function __construct ()
    {
        $this->created_time = date("Y-m-d H:i:s");    
    }
    
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCaption(): ?string
    {
        return $this->caption;
    }

    public function setCaption(?string $caption): self
    {
        $this->caption = $caption;

        return $this;
    }

    public function getLink(): ?string
    {
        return $this->link;
    }

    public function setLink(?string $link): self
    {
        $this->link = $link;

        return $this;
    }

    public function getUserUsername(): ?string
    {
        return $this->user_username;
    }

    public function setUserUsername(?string $user_username): self
    {
        $this->user_username = $user_username;

        return $this;
    }

    public function getInstaType(): ?string
    {
        return $this->insta_type;
    }

    public function setInstaType(?string $insta_type): self
    {
        $this->insta_type = $insta_type;

        return $this;
    }

    public function getInstaId(): ?string
    {
        return $this->insta_id;
    }

    public function setInstaId(?string $insta_id): self
    {
        $this->insta_id = $insta_id;

        return $this;
    }

    public function getLowResolution(): ?string
    {
        return $this->low_resolution;
    }

    public function setLowResolution(?string $low_resolution): self
    {
        $this->low_resolution = $low_resolution;

        return $this;
    }

    public function getStandardResolution(): ?string
    {
        return $this->standard_resolution;
    }

    public function setStandardResolution(?string $standard_resolution): self
    {
        $this->standard_resolution = $standard_resolution;

        return $this;
    }

    public function getThumbnail(): ?string
    {
        return $this->thumbnail;
    }

    public function setThumbnail(?string $thumbnail): self
    {
        $this->thumbnail = $thumbnail;

        return $this;
    }

    public function getTags(): ?string
    {
        return $this->tags;
    }

    public function setTags(?string $tags): self
    {
        $this->tags = $tags;

        return $this;
    }

    public function getLocation(): ?string
    {
        return $this->location;
    }

    public function setLocation(?string $location): self
    {
        $this->location = $location;

        return $this;
    }

    public function getCreatedTime(): ?string
    {
        return $this->created_time;
    }

    public function setCreatedTime(?string $created_time): self
    {
        $this->created_time = $created_time;

        return $this;
    }

    public function getLatitude(): ?float
    {
        return $this->latitude;
    }

    public function setLatitude(?float $latitude): self
    {
        $this->latitude = $latitude;

        return $this;
    }

    public function getLongitude(): ?float
    {
        return $this->longitude;
    }

    public function setLongitude(?float $longitude): self
    {
        $this->longitude = $longitude;

        return $this;
    }

    public function getResponseJson(): ?string
    {
        return $this->responseJson;
    }

    public function setResponseJson(?string $responseJson): self
    {
        $this->responseJson = $responseJson;

        return $this;
    }

    public function getLikes(): ?int
    {
        return $this->likes;
    }

    public function setLikes(?int $likes): self
    {
        $this->likes = $likes;

        return $this;
    }

}

src/Form/InstaType.php
<?php

namespace App\Form;

use App\Entity\Insta;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class InstaType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('caption')
            ->add('link')
            ->add('user_username')
            ->add('insta_id')
            ->add('low_resolution')
            ->add('standard_resolution')
            ->add('thumbnail')
            ->add('tags')
            ->add('location')
            ->add('created_time')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Insta::class,
        ]);
    }
}

src/Controller/InstaController.php
<?php

namespace App\Controller;

use App\Entity\Insta;
use App\Form\InstaType;
use App\Repository\InstaRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
 
use Symfony\Component\HttpFoundation\JsonResponse;


/**
 * @Route("/admin/insta")
 */
class InstaController extends AbstractController
{
    /**
     * @Route("/", name="insta_index", methods="GET")
     */
    public function index(InstaRepository $instaRepository): Response
    {
        return $this->render('insta/index.html.twig', ['instas' => $instaRepository->findAll()]);
    }

    /**
     * @Route("/search", name="insta_search", methods="GET|POST")
     */
    public function search (Request $request, InstaRepository $instaRepository) 
    {
        
        // https://www.instagram.com/developer/endpoints/media/
        // https://api.instagram.com/v1/locations/search?lat=43.3&lng=5.4&access_token=8439782101.da06fb6.51b1b6f220384c2c8a7e7318cc33ab65
        /*
        zonage en 10x10
        (44 - 42.8) / 10    = 0.12
        (7 - 4) / 10        = 0.3
                        
        */
        $lat        = floatval($request->get("lat",      $_GET['lat']));
        $lng        = floatval($request->get("lng",      $_GET['lng']));
        
        // $distance   = $request->get("distance", 5000);
        $distance   = 5000;     // ON FORCE LA DISTANCE MAX POUR OBTENIR UNE COUVERTURE MAXIMALE
        
        $latRef     = intval($lat * 10) * 0.1;
        $lngRef     = intval($lng * 20) * 0.05;
        
        $tabResponse = [];
        
        $objInsta   = $instaRepository->findOneBy([ "insta_type" => "API", "latitude" => $latRef, "longitude" => $lngRef ]);
        $em = $this->getDoctrine()->getManager();
        if ($objInsta != null) {
            $txtJsonResponse    = $objInsta->getResponseJson();
            $dateCreation       = $objInsta->getCreatedTime();
            $timeCreation       = strtotime($dateCreation);
            $now                = time();
            
            // TEST SI LA DERNIERE REQUETE EST TROP VIEILLE (300s => 5min)
            if ($now - $timeCreation > 300) {
                // ON OUBLIE LA DERNIERE REPONSE
                $em->remove($objInsta);
                $em->flush();

                // ET ON VA RAFRAICHIR LA REPONSE
                $objInsta = null;
            }
        }
        
        if ($objInsta == null) {
            $urlApi             = "https://api.instagram.com/v1/media/search?lat=$latRef&lng=$lngRef&distance=$distance&access_token=8439782101.da06fb6.51b1b6f220384c2c8a7e7318cc33ab65";
            $txtJsonResponse    = file_get_contents($urlApi);
            
            if ($txtJsonResponse) {

                $objInsta = new Insta;
                $objInsta->setLatitude($latRef);
                $objInsta->setLongitude($lngRef);
                $objInsta->setResponseJson($txtJsonResponse);
                $objInsta->setInstaId(0);
                $objInsta->setInstaType("API");
                
                $em->persist($objInsta);


                // EXTRACT ALL POINTS IN JSON RESPONSE                
                $tabJson                = json_decode($txtJsonResponse, true);
                $tabData                = $tabJson["data"] ?? [];
                foreach($tabData as $index => $tabPost) {
                    $postId             = $tabPost["id"] ?? 0;
                    
                    $postLatitude       = $tabPost["location"]["latitude"] ?? 43.3;
                    $postLongitude      = $tabPost["location"]["longitude"] ?? 5.4;
                    $postLink           = $tabPost["link"] ?? "";
                    $postUsername       = $tabPost["user"]["username"] ?? "";
                    $postCreatedTime    = $tabPost["created_time"] ?? "";
                    $postImageThumbnail = $tabPost["images"]["thumbnail"]["url"] ?? "";
                    $postImageLR        = $tabPost["images"]["low_resolution"]["url"] ?? "";
                    $postImageSR        = $tabPost["images"]["standard_resolution"]["url"] ?? "";
                    $postCaption        = $tabPost["caption"]["text"] ?? "";
                    
                    $objInstaPost   = $instaRepository->findOneBy([ "insta_id" => $postId ]);
                    if ($objInstaPost == null) {
                        // NEW INSTA
                        $objInstaPost = new Insta;
                        
                        $objInstaPost->setInstaType("insta");
                        $objInstaPost->setInstaId($postId);
                        $objInstaPost->setLatitude($postLatitude);
                        $objInstaPost->setLongitude($postLongitude);
                        $objInstaPost->setLink($postLink);
                        $objInstaPost->setUserUsername($postUsername);
                        $objInstaPost->setCreatedTime($postCreatedTime);
                        $objInstaPost->setThumbnail($postImageThumbnail);
                        $objInstaPost->setLowResolution($postImageLR);
                        $objInstaPost->setStandardResolution($postImageSR);
                        $objInstaPost->setCaption($postCaption);
                        
                        $em->persist($objInstaPost);
                        
                    }
                    else {
                        // UPDATE DATA??
                    }
                            
                }
                
                $em->flush();
            }
        }

        $tabJson    = json_decode($txtJsonResponse, true);
        $tabResponse += $tabJson;
        
        return new JsonResponse($tabResponse);
    }

    /**
     * @Route("/new", name="insta_new", methods="GET|POST")
     */
    public function new(Request $request): Response
    {
        $instum = new Insta();
        $form = $this->createForm(InstaType::class, $instum);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($instum);
            $em->flush();

            return $this->redirectToRoute('insta_index');
        }

        return $this->render('insta/new.html.twig', [
            'instum' => $instum,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="insta_show", methods="GET")
     */
    public function show(Insta $instum): Response
    {
        return $this->render('insta/show.html.twig', ['instum' => $instum]);
    }

    /**
     * @Route("/{id}/edit", name="insta_edit", methods="GET|POST")
     */
    public function edit(Request $request, Insta $instum): Response
    {
        $form = $this->createForm(InstaType::class, $instum);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('insta_edit', ['id' => $instum->getId()]);
        }

        return $this->render('insta/edit.html.twig', [
            'instum' => $instum,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="insta_delete", methods="DELETE")
     */
    public function delete(Request $request, Insta $instum): Response
    {
        if ($this->isCsrfTokenValid('delete'.$instum->getId(), $request->request->get('_token'))) {
            $em = $this->getDoctrine()->getManager();
            $em->remove($instum);
            $em->flush();
        }

        return $this->redirectToRoute('insta_index');
    }
    
    
}

templates/insta/_delete_form.html.twig
                    <form method="post" class="InstAdmin" action="{{ path('insta_delete', {'id': instum.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
                    <input type="hidden" name="_method" value="DELETE">
                    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ instum.id) }}">
                    <button class="btn-danger" title="Supprimer"><i class="fas fa-trash"></i></button>
                    </form>

templates/insta/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Enregistrer') }}</button>
{{ form_end(form) }}

templates/insta/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edition Instagram{% endblock %}

{% block body %}
    <h1 class="InstAdmin">Edition Instagram</h1>
    <img src="{{ instum.StandardResolution }}" alt="" class="Insta" />
    <div class="InstAdmin">
    
    <div class="centre margin"><a href="{{ path('insta_index') }}"><button class="btn" title="Retour à la liste"><i class="fas fa-reply"></i></button></a></div>
    <div class="">{{ include('insta/_form.html.twig', {'button_label': 'Sauve'}) }}</div>
    <div class="centre"><a href="{{ path('insta_index') }}"><button class="btn" title="Retour à la liste"><i class="fas fa-reply"></i></button></a></div>
    </div>
    <br />
    <div class="centre">{{ include('insta/_delete_form.html.twig') }}</div>
{% endblock %}

templates/insta/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Feed Instagram{% endblock %}

{% block body %}
    <h1 class="InstAdmin">Feed Instagram</h1>
    <div class="InstAdmin"><a href="{{ path('insta_new') }}"><button class="btn" title="Ajouter"><i class="fa fa-plus"></i></button></a></div>
    <table class="table InstAdmin">
        <thead>
            <tr>
                <th>Id</th>
                <th>Standard_resolution</th>
                <th>Created_time</th>
                <th>latitude</th>
                <th>longitude</th>
                <th>responseJson</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for instum in instas %}
            <tr>
                <td>{{ instum.id }}</td>
                <td><div class="InstAdminImg"><img src="{{ instum.StandardResolution }}" alt=""></div></td>
                <td>{{ instum.createdTime }}</td>
                <td>{{ instum.latitude }}</td>
                <td>{{ instum.longitude }}</td>
                <td>{{ instum.responseJson }}</td>
                <td>
                    <a href="{{ path('insta_show', {'id': instum.id}) }}"><button class="btn" title="Consulter"><i class="fa fa-eye"></i></button></a><br />
                    <a href="{{ path('insta_edit', {'id': instum.id}) }}"><button class="btn" title="Editer"><i class="fa fa-pen"></i></button></a>
                    <form method="post" action="{{ path('insta_delete', {'id': instum.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
                    <input type="hidden" name="_method" value="DELETE">
                    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ instum.id) }}">
                    <button class="btn-danger" title="Supprimer"><i class="fas fa-trash"></i></button>
                    </form>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="13">Aucun enregistrement trouvé</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <div class="InstAdmin"><a href="{{ path('insta_new') }}"><button class="btn" title="Ajouter"><i class="fa fa-plus"></i></button></a></div>
{% endblock %}

templates/insta/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Insta{% endblock %}

{% block body %}
    <h1>Create new Insta</h1>

    {{ include('insta/_form.html.twig') }}

    <a href="{{ path('insta_index') }}">back to list</a>
{% endblock %}

templates/insta/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Insta{% endblock %}

{% block body %}
    <h1 class="InstAdmin">Instagram</h1>
    <div class="InstAdmin centre padding">
    <a href="{{ path('insta_index') }}"><button class="btn" title="Retour à la liste"><i class="fas fa-reply"></i></button></a>
    <a href="{{ path('insta_edit', {'id': instum.id}) }}"><button class="btn" title="Editer"><i class="fa fa-pen"></i></button></a>
    </div>

        <img src="{{ instum.StandardResolution }}" alt="" class="Insta" />

    <div class="centre padding">
        {{ include('insta/_delete_form.html.twig') }}
        <br />
    </div>
    <table class="table InstAdmin">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ instum.id }}</td>
            </tr>
            <tr>
                <th>Caption</th>
                <td>{{ instum.caption }}</td>
            </tr>
            <tr>
                <th>Link</th>
                <td>{{ instum.link }}</td>
            </tr>
            <tr>
                <th>User_username</th>
                <td>{{ instum.userUsername }}</td>
            </tr>
            <tr>
                <th>Type</th>
                <td>{{ instum.instaType }}</td>
            </tr>
            <tr>
                <th>Insta_id</th>
                <td>{{ instum.instaId }}</td>
            </tr>
            <tr>
                <th>Low_resolution</th>
                <td>{{ instum.lowResolution }}</td>
            </tr>
            <tr>
                <th>Standard_resolution</th>
                <td>{{ instum.standardResolution }}</td>
            </tr>
            <tr>
                <th>Thumbnail</th>
                <td>{{ instum.thumbnail }}</td>
            </tr>
            <tr>
                <th>Tags</th>
                <td>{{ instum.tags }}</td>
            </tr>
            <tr>
                <th>Location</th>
                <td>{{ instum.location }}</td>
            </tr>
            <tr>
                <th>Created_time</th>
                <td>{{ instum.createdTime }}</td>
            </tr>
        </tbody>
    </table>   
{% endblock %}